# zsh-aliases: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  app:
    environment: &environment
      - APP_NAME=zsh-aliases
    build:
      context: .
      dockerfile: docker/app-test/Dockerfile
